### ISSUE TITLE
Aligned fraction reported by triangle mode

### ISSUE THREAD

**Issue by donovan-h-parks** [bluenote-1577/skani#14]
Hi,

The aligned fraction (AF) between two genomes is not symmetrical. The `search` and `dist` modes handle this be reporting the AF with respect to both the reference and query. When running in `triangle` mode, only the lower triangle is provided? How should this be interpreted? Is it possible to return the full AF matrix to account for this measure not being symmetric?

Thanks,
Donovan

**Comment by donovan-h-parks** [comment]
Hi Jim,

Thanks for pointing out the `--full-matrix` options. This is great. Perhaps the AF matrix should always be a full matrix and the optional flag just impacts the ANI matrix.

Thanks,
Donovan

**Comment by bluenote-1577** [comment]
I definitely agree. I made AF matrix always square in the latest commit. It's updated in the repo and in the static binary now. 

I'll leave this issue up until I get around to updating the conda version.

**Comment by donovan-h-parks** [comment]
Great - thanks Jim.
