### ISSUE TITLE
skani as library restricted to 1 thread

### ISSUE THREAD

**Issue by AroneyS** [bluenote-1577/skani#19]
We have a tool called Galah (https://github.com/wwood/galah) that uses ANI methods to cluster genomes. We implemented skani based on the example (https://github.com/bluenote-1577/skani-lib-example), here: https://github.com/wwood/galah/blob/e9e59a8c9b95f0fcbf034d8d8d505a4c631e69e2/src/skani.rs#L68. Galah also uses rayon, initialised here: https://github.com/wwood/galah/blob/e9e59a8c9b95f0fcbf034d8d8d505a4c631e69e2/src/main.rs#L32.

When we run Galah using finch/fastANI, it uses the provided threads but when we run it with skani, it is restricted to 1 thread. Any ideas?

**Comment by bluenote-1577** [comment]
Hi @AroneyS,

Few comments about your implementation. I took a brief look but have not dived through your code too deeply. It appears you have `clusterer`s and `preclusterer`s, and you can use skani for both. I see no reason why the skani `clusterer` should not be multi-threaded if your FastANI implementation is, given the interface is the same... but for the `preclusterer`:

It appears that in the line [here](https://github.com/wwood/galah/blob/e9e59a8c9b95f0fcbf034d8d8d505a4c631e69e2/src/skani.rs#L24) that you're running for loops that are not parallelized. 

skani, like FastANI, only does parallelization by parallelizing computations over batches; it does not do multithreading for a single genome-to-genome comparison (I think I accidentally implied this in the README, my bad). Thus in that line, I believe you will have to do a rayon par iter loop.  

**Unrelated but important note:** 
1. In the [`calculate_skani`](https://github.com/wwood/galah/blob/e9e59a8c9b95f0fcbf034d8d8d505a4c631e69e2/src/skani.rs#L64) function, you're sketching the reference and then calculating ANI. It would be far more efficient to sketch the reference only once for all genomes, and then use these sketches for the actual ANI calculation; sketching can take up to a magnitude longer than distance calculation. 
2. I recommend using the ANI regression workflow shown [here](https://github.com/bluenote-1577/skani-lib-example/blob/main/src/main.rs#L70). My implementation of skani uses this regression and it helps quite a lot for ANIs between 90-97ish.
3. You can get a big speedup by filtering out references by "screening" them without actually chaining and calculating ANI if you have a genomes that are diverse and not related to each other. The code shown in an older version of my [triangle.rs](https://github.com/bluenote-1577/skani/blob/v0.1.5/src/triangle.rs#L60) file may be of use... but I apologize for the lack of documentation

**Comment by AroneyS** [comment]
Oh good catch! Thanks for the suggestions too. I was also considering just running skani triangle on all the genomes beforehand and then have calculate_skani access the pre-calculated values.
