### ISSUE TITLE
support for arm64 neon

### ISSUE THREAD

**Issue by jianshu93** [bluenote-1577/skani#2]
Hello skani team,

Many thanks for this amazing tool further accelerating ANI calculation. I saw that compiling on macOS arm64 failed because of:

error[E0432]: unresolved import `std::arch::x86_64`

and all SIMD operations. I think for the nightly rust, ARM neon is fully supported and add support will be very useful of new Mac users. We are the FastANI team here at Georgia Tech, together with fast genomic search tools: https://github.com/jianshu93/gsearch

Thanks,

Jianshu

**Comment by bluenote-1577** [comment]
Hi @jianshu93,

Thanks for pointing this out. To be honest, I'm not sure what the best method of resolving this issue is (I'm not familiar with packaging and nightly rust etc). Do you have any suggestions?

For now, I created a branch called no-simd in the repository. Perhaps you can try installing with that branch? I've removed dependence of std::arch::x86_64.

**Comment by jianshu93** [comment]
Hello Jim,

https://moshg.github.io/rust-std-ja/std/arch/aarch64/index.html and here: https://moshg.github.io/rust-std-ja/core/arch/aarch64/index.html


you can find the arm64/aarch64 vector types, hopefully all types you used for 86_64 can be found. 

It seems the jmalloc problem on MacOS arm64 for the non-sims version (sims version ok on intel macOS):


warning: unused import: `natord::*`
 --> src/file_io.rs:6:5
  |
6 | use natord::*;
  |     ^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `skani` (lib) generated 1 warning (run `cargo fix --lib -p skani` to apply 1 suggestion)
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/bin:/Users/jianshuzhao/Github/bowtie2-2.5.0-macos-arm64:/opt/homebrew/bin:/Users/jianshuzhao/bin:/opt/homebrew/opt/bzip2/bin:/Users/jianshuzhao/Github/mummer-4.0.0beta5/bin:/Users/jianshuzhao/go/bin:/Users/jianshuzhao/Github/hmmer-h3-arm/bin:/opt/homebrew/opt/llvm/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/Cellar/coreutils/9.0/bin:/opt/homebrew/opt/ruby/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/jianshuzhao/.cargo/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/bin:/opt/X11/bin" VSLANG="1033" ZERO_AR_DATE="1" "cc" "-arch" "arm64" "/var/folders/mr/8qybn91j5fgdbrcdmq7ckftw0000gn/T/rustcJWZ2DJ/symbols.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.0.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.1.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.10.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.11.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.12.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.13.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.14.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.15.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.2.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.3.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.4.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.5.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.6.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.7.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.8.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.skani.d1219f4b-cgu.9.rcgu.o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d.g642ebwxp4qewzx.rcgu.o" "-L" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps" "-L" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/build/bzip2-sys-8707ec8297953a83/out/lib" "-L" "/opt/homebrew/Cellar/xz/5.4.1/lib" "-L" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/build/tikv-jemalloc-sys-316b42233cf09474/out/build/lib" "-L" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libtikv_jemallocator-cfd82a17d471738a.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libtikv_jemalloc_sys-030dc28bb41c673e.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libskani-33b6eaf3e7f3af20.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbincode-af6c529b3691637d.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libfastrand-9f4cac3b77876b06.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libsimple_logging-98dc663ec6af4418.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libthread_id-e04459ef1eaf5772.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/librust_lapper-f004547a9d11d4b9.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libneedletail-4206a4f63edbbf95.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbuf_redux-cdf9939c36e3fd3d.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libsafemem-3707a0a0adf79599.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libxz2-778e7325921de193.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/liblzma_sys-956804e08492fb19.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libflate2-085473bcaf95518d.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libminiz_oxide-7c351839885ef311.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libadler-ea2f03bed27697c6.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libcrc32fast-1b17169872747ce1.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbzip2-0b3338980f3e7c12.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbzip2_sys-6efdf5e81bd34bc1.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libnatord-7e7d3e7baf2ef3da.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbio-1cac8a395e430687.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libstrum-2aef9fafb37cf209.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libcsv-b8df4301cd3096fc.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libryu-bedbeaf8fb82e951.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libitoa-529c4fc1f440143a.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libcsv_core-16048d49f4b1bee9.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbstr-10e672eafa56dbe3.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libregex_automata-7e39cc66579080d7.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbytecount-7cc824ab8179eed5.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libtriple_accel-07174000e7f6558f.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libitertools_num-8e702c9eab0e8a2f.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libenum_map-2f0f5943c731aa69.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libstatrs-cc2c75d38c49e5b5.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libnalgebra-4cb0b0f600da0bef.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/librand_distr-f7ddc9c9272ea87e.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libnum_rational-f9c22763cc28bf57.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libtypenum-e93a2e3516cd2d2f.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libsimba-31abb76bc4bab297.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libwide-d7a667aa9063ea47.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbytemuck-f9fbdbd3406f2fbb.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libsafe_arch-83bb09f3ac489570.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/librand-8a49a13f9e4a4966.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/librand_chacha-5a34e413745de0e0.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libppv_lite86-4c7371c1341e0bc7.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/librand_core-0e8da056dadb270c.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libgetrandom-95e48b62cb529d86.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libordered_float-18e20046f77d3bf0.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libndarray-da188126b31777c6.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libmatrixmultiply-dd4b0b7351dfa17a.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libnum_complex-02b3a70e3d98366b.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/librawpointer-19ec78037436d9a8.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libmultimap-45d7d2c833f8219e.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libitertools-30beb20afe67e879.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libanyhow-ecbdb644a0ba7b53.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbv-de2ee6351851cbbd.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libvec_map-0ee75c180fc3c643.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbio_types-57aa92c280d65dbe.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libthiserror-bc18f69d275e48f7.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libregex-dfdb14183a878fc6.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libaho_corasick-33eeaf37036ec56b.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libmemchr-54f0409dfa166271.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libregex_syntax-13bb58b87537387c.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libpetgraph-d5d6e0e52b266fbb.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libfixedbitset-ac6827309c8da6ff.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libnewtype_derive-c998b55e43562f95.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/liblazy_static-51c906eac0170e91.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libcustom_derive-96b91977a1ee21dc.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libapprox-c9cd67bb18b946e5.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libfxhash-16a681e694f2bdc0.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbyteorder-30b0a44e508c3016.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/liblog-9143286386983759.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libpartitions-d4a5fc97aa16bdf4.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/librayon-40462157743cad1a.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/librayon_core-a03593450e2fede9.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libnum_cpus-6132c7e1012e86cc.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libcrossbeam_deque-d98658c24f3d2865.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libcrossbeam_epoch-d6d31012b5cd2224.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libmemoffset-ed0476dc30853862.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libscopeguard-0ebe74a2a6112c80.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libcrossbeam_channel-5b1226dcd1e6ad28.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libcrossbeam_utils-1cb07b2b2ed39342.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libcfg_if-fd2b7116ccd09ced.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libeither-d09523b3f454d77e.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbit_vec-ab76fcb424304d65.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libsmallvec-bc01789276f9d121.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libserde-9c1115d9796844c8.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libinterval-341f84e2087a6768.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libgcollections-77fa0e909e86c2fa.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libtrilean-75b3d7d0f19c4a16.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbit_set-0f610fe7fb71433f.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbit_vec-67c7139a4131e2ff.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libnum_integer-d57ee07ea1c861ef.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libnum_traits-aba922aedec4a163.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libclap-8e02402045f6a396.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libatty-73a4d2f212fa9e08.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/liblibc-70682a3866e8bec9.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libstrsim-79915e59f3ec8d5a.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libtermcolor-6f965b3a1acbedce.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libtextwrap-8a0b507e8fa1219a.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libclap_lex-b40d20d9281c075a.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libos_str_bytes-f508449565a2cebc.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libindexmap-54979b7f042b06ec.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libhashbrown-b3cbb78c5254258a.rlib" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/libbitflags-3d2e3b166b3bc54a.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd-65231eff973b4392.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libpanic_abort-2b522f2fd3b33cb1.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libobject-a11910e6b39a313d.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libmemchr-98e2432a46ce6838.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libaddr2line-f5edf9223bdf3271.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libgimli-2ed9e16d77ae2572.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_demangle-ebe023ba90cb145c.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libstd_detect-51a1bb03a9e9d927.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libhashbrown-f503a537f1b253d1.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libminiz_oxide-84ee9cafbd4fd057.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libadler-d137511abda54d92.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_alloc-7aebb49ef1eedb7b.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libunwind-bd5d5720720598df.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcfg_if-190c7abd6e8e03ea.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liblibc-c881fe47a0a6ef18.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/liballoc-26076234e596ba3a.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/librustc_std_workspace_core-a8a859a864856684.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcore-908209eee60fb642.rlib" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib/libcompiler_builtins-5aa4ec02992215b2.rlib" "-llzma" "-liconv" "-lSystem" "-lc" "-lm" "-L" "/Users/jianshuzhao/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/jianshuzhao/Downloads/skani-no-simd/target/release/deps/skani-f125b8d6ea965c3d" "-Wl,-dead_strip" "-nodefaultlibs"
  = note: Undefined symbols for architecture arm64:
            "___aarch64_cas8_relax", referenced from:
                __rjem_je_stats_interval_event_handler in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(stats.pic.o)
            "___aarch64_ldadd4_rel", referenced from:
                __rjem_je_arena_init in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(jemalloc.pic.o)
                _malloc_init_hard in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(jemalloc.pic.o)
                __rjem_je_arena_choose_hard in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(jemalloc.pic.o)
            "___aarch64_ldadd4_relax", referenced from:
                __rjem_je_arena_choose_hard in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(jemalloc.pic.o)
                __rjem_je_arena_nthreads_inc in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(arena.pic.o)
                __rjem_je_arena_nthreads_dec in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(arena.pic.o)
                __rjem_je_malloc_mutex_lock_slow in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(mutex.pic.o)
                __rjem_je_tsd_global_slow_inc in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(tsd.pic.o)
                __rjem_je_tsd_global_slow_dec in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(tsd.pic.o)
            "___aarch64_ldadd8_relax", referenced from:
                _a0idalloc in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(jemalloc.pic.o)
                _a0ialloc in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(jemalloc.pic.o)
                __rjem_realloc in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(jemalloc.pic.o)
                __rjem_je_arena_extent_alloc_large in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(arena.pic.o)
                __rjem_je_arena_extent_dalloc_large_prep in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(arena.pic.o)
                __rjem_je_arena_extent_ralloc_large_shrink in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(arena.pic.o)
                __rjem_je_arena_extent_ralloc_large_expand in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(arena.pic.o)
                ...
            "___aarch64_swp1_acq", referenced from:
                __rjem_je_tsd_slow_update in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(tsd.pic.o)
                __rjem_je_tsd_state_set in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(tsd.pic.o)
                __rjem_je_tsd_fetch_slow in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(tsd.pic.o)
                __rjem_je_malloc_tsd_boot1 in libtikv_jemalloc_sys-030dc28bb41c673e.rlib(tsd.pic.o)
          ld: symbol(s) not found for architecture arm64
          collect2: error: ld returned 1 exit status
          

error: could not compile `skani` due to previous error



Jianshu

**Comment by yunwilliamyu** [comment]
It does seem like fully supporting this will require some conditional compilation config options. Thanks so much for bringing this to our attention!

**Comment by bluenote-1577** [comment]
Hi @jianshu93,

Thanks again for reporting the issue on the new branch. 

I've removed the jemalloc allocator and have switched to using the default allocator on the no-simd branch. The only reason I switched allocators was because I need it for compiling static binaries on linux, but it shouldn't be an issue otherwise.

Let me know if it resolves the issue. If not, I'll have to secure access to arm64 machine...

Thanks,

Jim

**Comment by yunwilliamyu** [comment]
@bluenote-1577: We can spin up an Arm machine on Google Cloud, I think. Let's talk about that at our next meeting.

**Comment by jianshu93** [comment]
Hello Jim,

Thanks for the quick response and yes I can successfully compile it now on the ARM64 macOS.

From my experience, shifting to pure static compiling via musl, despite using a different allocator, affect the rayon parallel efficiency (maybe not very much in your case). It is ok (I feel) to have several system libraries dynamically linked like libc.so.6 or linux-vdso.so.1 or ld-linux-x86-64.so.2 because they are required for nearly all major linux distributions like CentOS, Ubuntu and RHEL. Maybe you can release it on crates.io and then everybody can use cargo install to install it without worrying static link.

Another advantage is that rust supports cross compiling, you can compile ARM64/aarch64 MacOS/linux binary on your x86_64 linux by adding the - - target feature and also installing corresponding gcc version for the target archetecture. You may need a real arm/aarch64 machine to test though in the end. I have no problem use it to compile aarch64 linux binary on my intel MacOS.

Thanks,

Jianshu
