### ISSUE TITLE
[Feature request] Many-to-many ANI comparisons

### ISSUE THREAD

**Issue by jolespin** [bluenote-1577/skani#22]
I want to try replacing `FastANI` with `Skani` in my workflow.  However, I need easy access to the _many vs. many_ utility.  For example, in `FastANI` I would do the following: `fastANI --ql [QUERY_LIST] --rl [REFERENCE_LIST] -o [OUTPUT_FILE]`

Can you add this functionality to `Skani`?

**Comment by bluenote-1577** [comment]
Hi @jolespin,

skani has this capability: try `skani dist --ql QUERY_LIST --rl REF_LIST -o OUTPUT`. 

Also, you can try `skani dist -q gn1.fa gn2.fa -r gn3.fa gn4.fa` too. 

Let me know if I've misunderstood something,

Jim

**Comment by jolespin** [comment]
No, that's definitely what I was trying to do. Amazing!

A few follow ups:
* Do you have an example of the output in what it looks like?
* How is the memory usage compared to FastANI (apologies if you discussed this in the paper)

**Comment by bluenote-1577** [comment]
It's about 10x less than fastani, although it depends on the exact parameters and settings. For genome level ani calculations, should be interchangeable with fastani.

**Comment by bluenote-1577** [comment]
The preset only determines -c and overrides it.

**Comment by jolespin** [comment]
Got it implemented.  Thanks!
