### ISSUE TITLE
skani outputting low number of comparisons 

### ISSUE THREAD

**Issue by Valentin-Bio** [bluenote-1577/skani#25]
Hello developer!, I'm testing Skani against a set of MAGs that I made by making all-to-all comparisons, I ran skani with the default parameters as the following: 

`skani dist -t 20 -q mags/*.fa -r mags/*.fa -o skani_petase_mags/mags_dist.txt`

given that I have 114 MAGs, I'm expecting to have 6421 rows (or pairwise combinations), so as I noticed, I'm getting only 178 comparisons. By looking at the documentation I see that you preset a minimum alignment fraction of 15%, which by understanding the program's sparse chainning algorithm, is a necessary step to detect orthologous regions. 

When I set `--min-af 0 ` I notice that I have more comparisons but still I'm getting a relatively low number of comparisons (206). so, the possible explanation for this is that there are no comparisons between all my MAGs because there is a null alignment fraction between the majority of those? or it might be that those comparisons fall outside the confidence interval in the ANI distribution?

bests,

Valentín.

**Comment by bluenote-1577** [comment]
Hi @Valentin-Bio,

Yes, skani only outputs results when the min-af is greater than some threshold. This explains why there's less than 6421 results. Some pointers:

1. Even with --min-af 0, skani may not have any successful mappings internally, so no result will be displayed.
2. skani really only works with ANI > 82-85%. Genus-level similarity ranges from 70-95% (rough estimate),  so for diverse mags from an arbitrary environment, most of them will not have comparisons. 
3. I do not recommend setting --min-af 0. skani's results will be unreliable in the regime where AF is small. 
4. P.S. Try `skani triangle -E mags/*.fa -o results.txt` to get the same thing but 2x faster.

**Comment by Valentin-Bio** [comment]
Thanks so much for the explanation and this great tool, I'll keep in mind your recommendation.
