### ISSUE TITLE
Triangle output interpretation

### ISSUE THREAD

**Issue by timyerg** [bluenote-1577/skani#36]
Hi!
First of all, thank you for the tool. 
I want to incorporate your tool into my workflow. Briefly, I have a fasta file with sequences. I need to find the representative sequence for the whole fasta file. I want to use your tool to find the sequence that is the most similar to the other sequences to be chosen. I ended up with:

`skani triangle -i rep_seqs.fasta -E -s 1 --min-af 1 > skani_ani_matrix.txt`

Then, I open the skani_ani_matrix.txt file, calculate the average ANI score for each sequence and sort it to choose the sequence with the highest average score.

Do I interpret the output correctly in this situation?

**Comment by bluenote-1577** [comment]
hi @timyerg ,

That sounds reasonable. But, I **strongly caution** using `--min-af 1`. I dont' know what types of sequences you're comparing. But this can happen:

suppose you have two genomes, A and B. If A and B are very different (e.g., different genus). Then their ANI is very small. But if there is some contamination or horizontal gene transfer, then you might have 99% ANI and 1% AF. In this case, the ANI is very misleading -- it is only 99% on 1% of the genome. 

So I would recommend you set an AF threshold, either in skani, or when you do your analysis elsewhere.

**Comment by timyerg** [comment]
Thank you for the answer. Looks like I misunderstood this parameter. That makes sense, good that you corrected me
