### ISSUE TITLE
I cannot install skani on my apple silicon

### ISSUE THREAD

**Issue by SilasK** [bluenote-1577/skani#37]
I tried with mamba and pixi specifying the bioconda channel

**Comment by bluenote-1577** [comment]
@SilasK the current conda recipe doesn't specify apple sillicon as a build option (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/skani/meta.yaml) -- only linux-aarch64. I think someone else added the ability to compile for linux-aarch64, not me. 

If you build skani using the rust compile instructions, does it work for apple silicon? If it does, I will enable osx-aarch64 builds.

**Comment by SilasK** [comment]
Yes, compiling works! 
I think in conda they have now the option to specify arm64 as system. But I don't know exactly how..

**Comment by bluenote-1577** [comment]
@SilasK merged into bioconda branch osx arm capabilities, lmk if it works.
