### ISSUE TITLE
skani for eukaryotic genomes

### ISSUE THREAD

**Issue by jianshu93** [bluenote-1577/skani#5]
Hello Jim，

Another question about skani，which happens to be the weakness of FastANI， very abundant kmers when anchoring，will be filtered for fastANI. This is ok for prokaryotes because nearly all genes are single copy. However， eukaryotic genomes have many copies of genes. Therefore，FastANI can not be used for eukaryotic genomes. I am wondering whether the sparse chaining idea here is subjected to this problem.

Thanks，

Jianshu

**Comment by bluenote-1577** [comment]
Hi Jianshu,

Thanks for the questions. I think this will be helpful for future users.

I don't think skani is suitable for complex eukaryotic genomes, but simple ones it seems to work okay. I do not think skani is suitable for say, human or plant genomes. 

The k-mer size is quite small, which means that some seeds are very abundant. It should however work for simpler eukaryotic genomes, e.g. yeast. It even works on Drosophila genomes. However, importantly, I have no guarantees on the accuracy. 

FYI: There is actually a repetitive k-mer masking procedure in skani, just like in minimap2, for genomes of size 20 MB that I left in there a long time ago. 

Jim

**Comment by jianshu93** [comment]
Hello Jim and also Yun,

Thanks for the response. It is clear to me. Another question related to skani is whether it is metric. I know it is symmetric. I think this is quite complicated question because with FracMinHash and also the new seeding and chaining algorithm it is difficult to derive the metric property. FastANI is clearly not metric, which limits its application in large scale searches using some graph/geometric ideas. 


Thanks,

Jianshu

**Comment by bluenote-1577** [comment]
skani is not a metric. Consider the following situation: Genome A and genome B are not related at all. But genome C is a 50% mix of genome A and genome B. In this situation, skani would output 100% ANI for comparing A and C, and 100% ANI for B and C, but nothing for A and B (i.e. the triangle inequality with 100 - ANI as the "metric" fails). Of course, skani would also output 50% aligned fraction for each comparison here. 

The question of how badly the triangle inequality fails in practice is an interesting question. This is not something I've explored fully.

**Comment by jianshu93** [comment]
Ok then this is cleat. Yeah very interesting topic. I think minhash (Jaccard) is metric but hyperminhash? I am considering feeding hyperminhash to some graph based search scheme, which requires metric as input. Still some thoughts but not mature yet.


Jianshu

**Comment by yunwilliamyu** [comment]
Hi Jianshu. MinHash and HyperMinHash are both sketches that estimate Jaccard index, which is not itself a metric. The only difference between the two is the space complexity required, but in terms of output, it is basically the same.

If you require a metric, you’ll need something like Jaccard distance = 1 - Jaccard index. But, my initial impression is that it is not a very nice metric, and then you also have to deal with the amount of fuzziness in using a (Hyper)MinHash approximation of it. So it’ll depend a lot on what kind of search scheme you want to feed it into.

**Comment by jianshu93** [comment]
Hello Yun,

Thanks for the response. In practice, I am wondering,  as long as we use enough sketches to approximate Jaccard index/distance to a level that the metric property of Jaccard distance is preserved well enough, then we should not worry too much about whether minhash/hyperminhash approximation is 100% metric or not. I am thinking using Hierarchical Navigable Small World Graphs, a nearest neighbor search idea, which requires metric distance as input. Creating/Storing sketches on disk for a very large number of genomes, like a million bacterial genome does take a lot of memory/space (if fully parallelized). Therefore, I am wondering whether replacing minhash with hyperminash could be an advantage. I have been trying ProbMinHash without problems. 

Thanks,

Jianshu

**Comment by yunwilliamyu** [comment]
HyperMinHash’s only advantage over MinHash is in space complexity. Typically, if you are normally use a 64-bit hash in MinHash, you could pretty reasonably reduce it down to a 16-bit hash using HyperMinHash. Think of it as storing lossily compressed versions of the hash values. Exactly how much compression you can get without losing accuracy depends on the problem domain.

In general, for most applications, I think you could replace MinHash with HyperMinHash, but the question is whether a factor 2-4 savings in the data structure space is worth the additional programming complexity (though the additional complexity is also fairly minimal).
