### ISSUE TITLE
Identical sequences have pairwise AF lower than 100%

### ISSUE THREAD

**Issue by apcamargo** [bluenote-1577/skani#7]
I'm testing `skani` to compute the pairwise ANI of all sequences within a FASTA file where each sequence is a genome. I noticed that when a genome is compared to itself, the resulting AF is lower than 100%. For example:

```
$ ./skani dist --qi --ri -r test.fna -q test.fna -o skani_output.tsv
```

```
Ref_file   Query_file   ANI      Align_fraction_ref   Align_fraction_query   Ref_name                  Query_name
--------   ----------   ------   ------------------   --------------------   -----------------------   -----------------------
test.fna   test.fna     100.00   86.91                86.91                  2001200001.a:2001201486   2001200001.a:2001201486
```

It could be because the sequence is short?

```
$ seqkit fx2tab -i -n -l test.fna
2001200001.a:2001201486	1230
```

Reducing `-c` improved the estimate:

```
$ ./skani dist -c 1 --qi --ri -r test.fna -q test.fna -o skani_output.tsv
```

```
Ref_file   Query_file   ANI      Align_fraction_ref   Align_fraction_query   Ref_name                  Query_name
--------   ----------   ------   ------------------   --------------------   -----------------------   -----------------------
test.fna   test.fna     100.00   98.13                98.13                  2001200001.a:2001201486   2001200001.a:2001201486
```

When I tried to change `-m` I got an error:

```
thread 'main' panicked at 'We currently don't allow c > 10', src/params.rs:153:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    8146 abort      ./skani dist -m 10 --qi --ri -r test.fna -q test.fna -o skani_output.tsv
```

**Comment by bluenote-1577** [comment]
Actually, looking through my code, I implemented a workaround to this issue a while back... but there was a bug and it wasn't applied correctly. I've pushed an approximate fix for this issue and it should give much more reasonable results now. 

The fix I implemented was simply adding "c" bases to the ends of the chains to account for the missing k-mers near the ends of the chains. This isn't perfect, but works _on average._ It still isn't a great fix for small sequences and doesn't guarantee 100% AF for identical sequences. 

I'll leave this issue up while I implement a better solution that guarantees 100% AF for identical sequences.

**Comment by apcamargo** [comment]
Thanks for the explanation, @bluenote-1577! I'll try out the latest commit and let you know if I have any issues.

**Comment by bluenote-1577** [comment]
Coming back to this issue -- most of the time the AF is 100% for identical genomes since 0.1.0, but it isn't technically guaranteed. I think this is okay, even if it's not 100% it'll be very very close, and we are an approximate method after all.

 If someone has issues with this or it fails spectacuarly in some cases, feel free to reference or open up this issue again.
